// ==========================================
// LIFE RPG PLANNER - Datos Simulados (Mock)
// Reemplazar con llamadas fetch a API .NET
// ==========================================

import { 
  IUser, IRole, IQuest, ISkill, IObjective, 
  ITimeBlock, ICampaign, IUserStats, IInvestment 
} from '@/types';

// Usuario de prueba
export const mockUser: IUser = {
  id: 'user-001',
  email: 'heroe@liferpr.com',
  username: 'ElGuerrero',
  avatar_url: undefined,
  level: 15,
  total_xp: 4250,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  mission: 'Convertirme en la mejor versión de mí mismo cada día',
  vision: 'Ser un líder que inspira a otros a alcanzar su máximo potencial',
};

// Roles/Clases del personaje
export const mockRoles: IRole[] = [
  {
    id: 'role-001',
    user_id: 'user-001',
    name: 'Desarrollador',
    description: 'Maestro del código y la tecnología',
    icon: 'Code2',
    color: 'primary',
    level: 23,
    current_xp: 750,
    xp_to_next_level: 1000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'role-002',
    user_id: 'user-001',
    name: 'Padre',
    description: 'Guardián y mentor de la familia',
    icon: 'Heart',
    color: 'destructive',
    level: 18,
    current_xp: 420,
    xp_to_next_level: 800,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'role-003',
    user_id: 'user-001',
    name: 'Atleta',
    description: 'Fortaleza física y mental',
    icon: 'Dumbbell',
    color: 'success',
    level: 12,
    current_xp: 200,
    xp_to_next_level: 600,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'role-004',
    user_id: 'user-001',
    name: 'Inversor',
    description: 'Construyendo libertad financiera',
    icon: 'TrendingUp',
    color: 'accent',
    level: 8,
    current_xp: 150,
    xp_to_next_level: 500,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'role-005',
    user_id: 'user-001',
    name: 'Estudiante',
    description: 'Aprendiz eterno del conocimiento',
    icon: 'BookOpen',
    color: 'secondary',
    level: 20,
    current_xp: 890,
    xp_to_next_level: 1000,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
];

// Misiones Diarias (Daily Quests)
export const mockQuests: IQuest[] = [
  {
    id: 'quest-001',
    user_id: 'user-001',
    role_id: 'role-001',
    title: 'Programar 2 horas de código enfocado',
    description: 'Sin distracciones, modo profundo',
    xp_reward: 100,
    frequency: 'daily',
    is_completed: false,
    streak: 5,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'quest-002',
    user_id: 'user-001',
    role_id: 'role-003',
    title: 'Completar rutina de ejercicio',
    description: '45 minutos de entrenamiento',
    xp_reward: 80,
    frequency: 'daily',
    is_completed: true,
    completed_at: new Date().toISOString(),
    streak: 12,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'quest-003',
    user_id: 'user-001',
    role_id: 'role-002',
    title: 'Tiempo de calidad con familia',
    description: '1 hora sin dispositivos',
    xp_reward: 60,
    frequency: 'daily',
    is_completed: false,
    streak: 8,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'quest-004',
    user_id: 'user-001',
    role_id: 'role-005',
    title: 'Leer 20 páginas',
    description: 'Lectura activa con notas',
    xp_reward: 50,
    frequency: 'daily',
    is_completed: false,
    streak: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'quest-005',
    user_id: 'user-001',
    role_id: 'role-004',
    title: 'Revisar portafolio de inversiones',
    description: 'Análisis semanal de activos',
    xp_reward: 40,
    frequency: 'weekly',
    is_completed: false,
    streak: 4,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
];

// Habilidades del árbol
export const mockSkills: ISkill[] = [
  // Skills de Desarrollador
  {
    id: 'skill-001',
    role_id: 'role-001',
    name: 'React Avanzado',
    description: 'Dominio de hooks, context y patrones avanzados',
    icon: 'Atom',
    cost_xp: 500,
    cost_time: '40 horas',
    is_unlocked: true,
    is_available: true,
    position_x: 0,
    position_y: 0,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'skill-002',
    role_id: 'role-001',
    name: 'TypeScript Pro',
    description: 'Tipos avanzados, generics y utilidades',
    icon: 'FileCode',
    cost_xp: 600,
    cost_time: '50 horas',
    is_unlocked: true,
    is_available: true,
    parent_skill_id: 'skill-001',
    position_x: 200,
    position_y: 0,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'skill-003',
    role_id: 'role-001',
    name: 'Arquitectura de Software',
    description: 'Patrones de diseño y clean architecture',
    icon: 'Building2',
    cost_xp: 800,
    cost_time: '60 horas',
    is_unlocked: false,
    is_available: true,
    parent_skill_id: 'skill-002',
    position_x: 400,
    position_y: 0,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'skill-004',
    role_id: 'role-001',
    name: '.NET Core',
    description: 'Backend con C# y .NET',
    icon: 'Server',
    cost_xp: 700,
    cost_money: 200,
    cost_time: '80 horas',
    is_unlocked: false,
    is_available: false,
    parent_skill_id: 'skill-002',
    position_x: 400,
    position_y: 150,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'skill-005',
    role_id: 'role-001',
    name: 'DevOps',
    description: 'CI/CD, Docker y Kubernetes',
    icon: 'Container',
    cost_xp: 900,
    cost_money: 150,
    cost_time: '100 horas',
    is_unlocked: false,
    is_available: false,
    parent_skill_id: 'skill-003',
    position_x: 600,
    position_y: 0,
    created_at: '2024-01-01T00:00:00Z',
  },
];

// Objetivos Trimestrales (Boss Battles)
export const mockObjectives: IObjective[] = [
  {
    id: 'obj-001',
    user_id: 'user-001',
    role_id: 'role-001',
    title: 'Lanzar MVP del Proyecto Personal',
    description: 'Completar y publicar la primera versión funcional',
    quarter: 'Q1',
    year: 2025,
    status: 'in_progress',
    xp_reward: 2000,
    deadline: '2025-03-31',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'obj-002',
    user_id: 'user-001',
    role_id: 'role-003',
    title: 'Correr Media Maratón',
    description: 'Completar 21km en menos de 2 horas',
    quarter: 'Q2',
    year: 2025,
    status: 'pending',
    xp_reward: 1500,
    deadline: '2025-06-30',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'obj-003',
    user_id: 'user-001',
    role_id: 'role-004',
    title: 'Alcanzar Fondo de Emergencia 6 meses',
    description: 'Ahorrar el equivalente a 6 meses de gastos',
    quarter: 'Q1',
    year: 2025,
    status: 'in_progress',
    xp_reward: 1800,
    deadline: '2025-03-31',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: new Date().toISOString(),
  },
];

// Bloques de Tiempo
export const mockTimeBlocks: ITimeBlock[] = [
  {
    id: 'block-001',
    user_id: 'user-001',
    role_id: 'role-001',
    title: 'Deep Work - Código',
    description: 'Tiempo de programación sin interrupciones',
    start_time: '06:00',
    end_time: '08:00',
    day_period: 'morning',
    block_type: 'focus',
    is_recurring: true,
    days_of_week: [1, 2, 3, 4, 5],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'block-002',
    user_id: 'user-001',
    role_id: 'role-003',
    title: 'Entrenamiento',
    description: 'Rutina de ejercicio matutino',
    start_time: '08:30',
    end_time: '09:30',
    day_period: 'morning',
    block_type: 'focus',
    is_recurring: true,
    days_of_week: [1, 2, 3, 4, 5],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'block-003',
    user_id: 'user-001',
    title: 'Almuerzo y Descanso',
    start_time: '12:00',
    end_time: '13:00',
    day_period: 'afternoon',
    block_type: 'rest',
    is_recurring: true,
    days_of_week: [1, 2, 3, 4, 5],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'block-004',
    user_id: 'user-001',
    role_id: 'role-001',
    title: 'Trabajo Principal',
    description: 'Tareas del trabajo',
    start_time: '09:30',
    end_time: '12:00',
    day_period: 'morning',
    block_type: 'focus',
    is_recurring: true,
    days_of_week: [1, 2, 3, 4, 5],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'block-005',
    user_id: 'user-001',
    role_id: 'role-002',
    title: 'Tiempo en Familia',
    description: 'Cena y actividades familiares',
    start_time: '18:00',
    end_time: '20:00',
    day_period: 'evening',
    block_type: 'focus',
    is_recurring: true,
    days_of_week: [0, 1, 2, 3, 4, 5, 6],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'block-006',
    user_id: 'user-001',
    role_id: 'role-005',
    title: 'Lectura y Aprendizaje',
    description: 'Tiempo de estudio personal',
    start_time: '21:00',
    end_time: '22:00',
    day_period: 'evening',
    block_type: 'focus',
    is_recurring: true,
    days_of_week: [1, 2, 3, 4, 5],
    created_at: '2024-01-01T00:00:00Z',
  },
];

// Campaña activa
export const mockCampaign: ICampaign = {
  id: 'campaign-001',
  user_id: 'user-001',
  name: 'Operación Génesis',
  description: 'El comienzo de la transformación total',
  quarter: 'Q1',
  year: 2025,
  theme: 'Fundamentos sólidos para el año',
  start_date: '2025-01-01',
  end_date: '2025-03-31',
  is_active: true,
  created_at: '2024-01-01T00:00:00Z',
};

// Estadísticas del usuario
export const mockStats: IUserStats = {
  total_quests_completed: 156,
  current_streak: 12,
  longest_streak: 45,
  objectives_completed: 3,
  total_xp_earned: 4250,
  hours_focused: 234,
};

// Inversiones
export const mockInvestments: IInvestment[] = [
  {
    id: 'inv-001',
    user_id: 'user-001',
    objective_id: 'obj-001',
    title: 'Curso de Arquitectura .NET',
    type: 'course',
    amount: 200,
    url: 'https://example.com/curso',
    status: 'in_progress',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'inv-002',
    user_id: 'user-001',
    objective_id: 'obj-002',
    title: 'Equipamiento de Running',
    type: 'tool',
    amount: 350,
    status: 'completed',
    created_at: '2024-01-01T00:00:00Z',
  },
];
